config/routes.rb
Rails.application.routes.draw do
  resources :addresses, only: [:update]
  resources :orders, param: :order_number, only: [:show] do
    resources :uploads, only: [:create]
    member do
      delete :destroy_uploads
      post :waiting_for_review
    end
  end

  devise_for :users, path: '/', path_names: { sign_in: '' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :order

  validates :street_1, :zip, :city, presence: true
  validates :zip, numericality: true

  def full_name
    return "#{gender == 1 ? 'Herr' : 'Frau'} #{academic_title} #{first_name} #{last_name}"
  end

  def glyphicon
	return 'glyphicon glyphicon-usd' if title == 'Rechnungsadresse'
  	return 'glyphicon glyphicon-send' if title == 'Lieferadresse'
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM
  belongs_to :admin_user
  has_one :user, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :uploads, dependent: :destroy
  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :user, allow_destroy: false

  after_initialize :generate_tokens

  validates :admin_user, :user, presence: true
  validates :order_number, uniqueness: true, numericality: true, length: { is: 5 }
  validates :security_key, numericality: true, length: { is: 5 }

  aasm do
    state :waiting_for_upload, :initial => true
    state :waiting_for_review
    state :in_production
    state :invoiced
    state :closed

    initial_state do
      OrderMailer.waiting_for_upload(self).deliver
    end

    event :waiting_for_review do
      after do
        OrderMailer.waiting_for_review(self).deliver
      end
      transitions :from => :waiting_for_upload, :to => :waiting_for_review
    end

    event :in_production do
      after do
        OrderMailer.in_production(self).deliver
      end
      transitions :from => :waiting_for_review, :to => :in_production
    end
  end

  def to_param
    return "#{order_number}"
  end

  private

  def generate_tokens
    return if self.order_number.present? && self.security_key.present?
    self.order_number = rand(11111..99999)
    self.security_key = rand(11111..99999)
  end
end

app/models/upload.rb
class Upload < ActiveRecord::Base
    belongs_to :order
    has_attached_file :attachment
    do_not_validate_attachment_file_type :attachment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable, authentication_keys: [:id]

  belongs_to :order
  before_create do |user|
    user.id = user.order.order_number if user.order.present?
  end

  def salutation
    if gender == 1
      return 'Sehr geehrter'
    else
      return 'Sehr geehrte'
    end
  end

  def full_name
    return "#{gender == 1 ? 'Herr' : 'Frau'} #{academic_title} #{first_name} #{last_name}"
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_filter :authenticate_user!

  def update
    @address = Address.find(params[:id])
    if @address.order.user_id == current_user.id
      @order.update(address_params)
    else
      render status :forbidden
    end
  end

  private

  def address_params
    params.require(:address).permit(:gender, :academic_title, :first_name, :last_name,
                                    :street_1, :street_2, :zip, :city, :phone, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    order_path(current_user.order) if current_user.present?
    admin_dashboard_path if current_admin_user.present?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @order = current_user.order
    redirect_to order_path(@order) if @order.order_number != params[:order_number].to_i
  end

  def destroy_uploads
    order = current_user.order
    order.uploads.delete_all
    redirect_to({action: :show})
  end

  def waiting_for_review
    order = current_user.order.waiting_for_review!
    redirect_to({action: :show})
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  def create
    if !params[:qqfile].blank?
      order = Order.where(order_number: params[:order_order_number]).first
      upload = order.uploads.build
      upload.attachment = params[:qqfile]
      if upload.save
        render :text => '{"success": true}'
      else
        render :text => upload.errors.to_yaml
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pionira</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="/bootstrap.min.css" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="container"><%= image_tag('pionira-logo.png', class: 'img-responsive') %></div>
</header>
<div id="content" class="container <%= 'skull' unless action_name.eql?('show') %>">
  <% flash.each do |type, message| %>
    <div class="alert alert-<%= type %>"><%= message %></div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/orders/_address.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <span class="<%= address.glyphicon %>"></span>
      <a data-toggle="collapse" data-parent="#order_data" href="#order_data_address_<%= address.id %>"><%= address.title %></a>
      <button style="float:right" type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#order_data_address_form_<%= address.id %>">Editieren</button>
    </h4>
  </div>
  <div id="order_data_address_<%= address.id %>" class="panel-collapse collapse">
    <div class="panel-body">
      <div class="form-group">
        <label class="control-label"><%= Address.human_attribute_name(:full_name) %></label>
        <span class="form-control"><%= address.full_name %></span>
      </div>
      <div class="form-group col-md-6 col-pad-right">
        <label class="control-label"><%= Address.human_attribute_name(:phone) %></label>
        <span class="form-control"><%= address.phone %></span>
      </div>
      <div class="form-group col-md-6 col-pad-left">
        <label class="control-label"><%= Address.human_attribute_name(:email) %></label>
        <span class="form-control"><%= address.email %></span>
      </div>
      <div class="form-group col-md-6 col-pad-right">
        <label class="control-label"><%= Address.human_attribute_name(:hospital) %></label>
        <span class="form-control"><%= address.hospital %></span>
      </div>
      <div class="form-group col-md-6 col-pad-left">
        <label class="control-label"><%= Address.human_attribute_name(:department) %></label>
        <span class="form-control"><%= address.department %></span>
      </div>
      <div class="form-group">
        <label class="control-label">Anschrift</label>
        <span class="form-control"><%= address.street_1 %> <%= address.street_2 %>, <%= address.zip %> <%= address.city %></span>
      </div>
      <div class="form-group">
        <label class="control-label">Referenznummer</label>
        <span class="form-control"><%= address.reference %></span>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="order_data_address_form_<%= address.id %>">
  <div class="modal-dialog">
    <%= form_for(address,remote: true, html: {class: 'modal-content', role: 'form'}) do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-dr_title">Auftrag bearbeiten</h4>
      </div>
      <div class="modal-body" style="padding-bottom: 0px;">
        <h4>Ansprechpartner</h4>
        <% [:first_name, :last_name, :phone, :email].each_with_index do |attribute,index| %>
          <div class="form-group col-sm-6 <%= index % 2 == 0 ? ' col-pad-right' : ' col-pad-left' %>">
            <%= f.label(attribute, class: "control-label") %>
            <%= f.text_field(attribute, class: 'form-control') %>
          </div>
        <% end %>
        <h4>Anschrift</h4>
        <% [:hospital, :department, :street_1, :street_2, :zip, :city].each_with_index do |attribute,index| %>
          <div class="form-group col-sm-6 <%= index % 2 == 0 ? ' col-pad-right' : ' col-pad-left' %>">
            <%= f.label(attribute, class: "control-label") %>
            <%= f.text_field(attribute, class: 'form-control') %>
          </div>
        <% end %>
        <h4>Sonstiges</h4>
        <div class="form-group col-sm-6">
          <%= f.label(:reference, class: "control-label") %>
          <%= f.text_field(:reference, class: 'form-control') %>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Abbrechen</button>
        <%= f.submit(Address.human_attribute_name("update"), class: 'btn btn-primary') %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/_in_production.html.erb
<div class="col-sm-6">
  <h2>In Produktion</h2>
</div>

app/views/orders/_invoiced.html.erb
<div class="col-sm-6">
  <h2>Rechnung gestellt</h2>
</div>

app/views/orders/_upload_modals.html.erb
<div class="modal fade" id="uploadProgress">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Dateien werden hochgeladen. <small>Bitte warten Sie bis der Vorgang abgeschlossen ist.</small></h4>
      </div>
      <div class="modal-body">
        <div class="progress progress-striped active">
          <div class="progress-bar" role="progressbar" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100" style="width: 15%"></div>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="uploadComplete">
  <div class="modal-dialog">
    <%= form_for(@order,remote: true, html: {class: 'modal-content form-horizontal', role: 'form'}) do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Vorgang abgeschlossen. <small>Wie möchten Sie fortfahren?</small></h4>
      </div>
      <div class="modal-body">
        <button type="button" class="btn btn-primary col-sm-5" data-dismiss="modal">Weitere Dateien hochladen</button>
        <%= link_to 'Daten versenden', waiting_for_review_order_url, :method => :post, :class => 'btn btn-success col-sm-5 col-md-offset-2' %>
        <div class="clearfix"></div>
      </div>
    <% end %>
  </div>
</div>

<div class="modal fade" id="uploadDelete">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Möchten Sie wirklich alle Dateien löschen?</h4>
      </div>
      <div class="modal-body">
        <button type="button" class="btn btn-primary col-sm-5" data-dismiss="modal">Abbrechen</button>
        <%= link_to 'Ja, alle Dateien löschen', destroy_uploads_order_url, :method => :delete, :class => 'btn btn-danger col-sm-5 col-md-offset-2' %>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>

app/views/orders/_waiting_for_review.html.erb
<div class="col-sm-6">
  <h2>Daten werden geprüft</h2>
</div>

app/views/orders/_waiting_for_upload.html.erb
<div class="col-sm-6">
  <div class="panel-group" id="order_file">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="glyphicon glyphicon-cloud-upload"></span>
          <a data-toggle="collapse" data-parent="#order_file" href="#order_file_upload">Schritt 1 von 3: Daten hochladen</a>
        </h3>
      </div>
      <div id="order_file_upload" class="panel-collapse collapse in">
        <div class="panel-body">
          <div id="uploader" class="col-md-6" style="padding-left: 0px;"></div>
          <div class="popover right in col-md-5 hidden-xs hidden-sm">
            <div class="arrow" style=""></div>
            <h3 class="popover-title"><span class="label label-success">Tipp:</span> Mehrfachauswahl</h3>
            <div class="popover-content">Markieren Sie alle Dateien gleichzeitig in der Ordneransicht.</div>
          </div>
        </div>
      </div>
    </div>
    <% if @order.uploads.size > 0 %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <span class="glyphicon glyphicon-cloud-upload"></span>
            <a data-toggle="collapse" data-parent="#order_file" href="#order_file_list">Vorhandene Dateien</a>
          </h3>
        </div>
        <div id="order_file_list" class="panel-collapse collapse in">
          <div class="panel-body">
            <table class="table" style="overflow: scroll; max-height: 220px; display: block;">
              <thead>
              <tr>
                <th>#</th>
                <th>Dateiname</th>
                <th>Format</th>
                <th>Größe</th>
              </tr>
              </thead>
              <tbody>
                <% @order.uploads.each_with_index do |upload, index| %>
                  <tr>
                    <td><%= index+1 %></td>
                    <td><%= upload.attachment_file_name %></td>
                    <td><%= upload.attachment_content_type %></td>
                    <td><%= number_to_human_size(upload.attachment_file_size) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <button type="button" class="btn btn-danger btn-sm btn-block" data-toggle="modal" data-target="#uploadDelete">Alle Dateien löschen?</button>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="progress progress-striped">
  <div class="progress-bar progress-bar-primary" style="width: 25%"><span>Datenupload</span></div>
  <div class="progress-bar progress-bar" style="width:25%; background-color: #A3A3A3;"><span>Datenfreigabe</span></div>
  <div class="progress-bar progress-bar" style="width:25%; background-color: #A3A3A3;"><span>In Produktion</span></div>
  <div class="progress-bar progress-bar" style="width:25%; background-color: #A3A3A3;"><span>Versand</span></div>
</div>
<%= render partial: @order.aasm_state %>
<div class="col-sm-6">
  <div class="panel-group" id="order_data">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="glyphicon glyphicon-pushpin"></span>
          <a data-toggle="collapse" data-parent="#order_data" href="#order_data_overview">Auftragsübersicht</a>
        </h3>
      </div>
      <div id="order_data_overview" class="panel-collapse collapse in">
        <div class="panel-body">
          <div class="form-group col-md-6 col-pad-right">
            <label class="control-label">Auftragsnummer</label>
            <span class="form-control"><%= @order.order_number %></span>
          </div>
          <div class="form-group col-md-6 col-pad-left">
            <label class="control-label">Sicherheitsschlüssel</label>
            <span class="form-control"><%= @order.security_key %></span>
          </div>
          <label class="control-label">Ihr Persönlicher Ansprechpartner</label>
          <address>
            <%= @order.admin_user.first_name %> <%= @order.admin_user.last_name %><br />
            <abbr title="Phone">T:</abbr> <%= @order.admin_user.phone %><br />
            <abbr title="Email">E:</abbr> <%= @order.admin_user.email %>
          </address>
        </div>
      </div>
    </div>
    <%= render partial: "address", collection: @order.addresses %>
  </div>
</div>
<%= hidden_field_tag 'order_uploads_url', order_uploads_url(order_order_number: @order.order_number) %>
<%= render partial: "upload_modals" %>
<script type="text/template" id="qq-template-bootstrap">
  <div class="qq-uploader-selector qq-uploader span12">
    <span class="btn btn-success qq-upload-button-selector qq-upload-button">
      <i class="glyphicon glyphicon-plus"></i>
      <span>Dateien auswählen</span>
    </span>
    <ul class="qq-upload-list-selector qq-upload-list" style="margin-top: 10px; text-align: center;">
      <li>
        <div class="qq-progress-bar-container-selector">
          <div class="qq-progress-bar-selector qq-progress-bar"></div>
        </div>
        <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
        <span class="qq-upload-file-selector qq-upload-file"></span>
        <span class="qq-upload-size-selector qq-upload-size"></span>
        <a class="qq-upload-cancel-selector qq-upload-cancel" href="#">Cancel</a>
        <span class="qq-upload-status-text-selector qq-upload-status-text"></span>
      </li>
    </ul>
  </div>
</script>
<%= javascript_include_tag "fineuploader/app", "data-turbolinks-track" => true %>